import { Button } from '@nextui-org/react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { MainLayout } from '../components/layouts'
import { Lists } from '../components/ui/lists'

import { FaPlus } from 'react-icons/fa'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const handleCreateList = () => {
    console.log('[handleCreateList] --> Button clicked')
  }

  return (
    <>
      <MainLayout title="Home">
        <>
          <Head>
            {/* <title>Create Next App</title> */}
            {/* <meta name="description" content="Generated by create next app" /> */}
          </Head>
          <Lists />

          <Button
            onClick={handleCreateList}
            css={{
              position: 'fixed',
              right: '1rem',
              bottom: '1rem',
              borderRadius: '50%',
              width: '50px',
              height: '50px',
              paddingLeft: '0',
              paddingRight: '0',
            }}
            auto
            color="primary"
            icon={<FaPlus fill="white" size={15} />}
          />
        </>
      </MainLayout>
    </>
  )
}

export default Home
